/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

var fibArr = [0,1];
var i=2;

// build the fib array less than 4 million
while( i < 100){
  var a = fibArr[i-2];
  var b = fibArr[i-1];
  var newFibonacci = a + b;
  if(newFibonacci >= 4000000){
    break
  } else {
      fibArr.push(newFibonacci)
      i++
  }
}

// remove the first two values since they are duplicates
fibArr.shift()
fibArr.shift()

// build the sum of only the even numbers using a modulo opperation
var sum = 0
for(var j=0; j < fibArr.length; j++){
  if((fibArr[j] / 2) % 1 === 0){
    sum += fibArr[j];
  }
}

console.log(sum)